### ISSUE TITLE
Support Actions

### ISSUE THREAD

**Issue by Jab2870** [fufar/simple-clock-card#24]
Do you have any interest in adding support for tap_action, hold_action and so on?

```yaml
type: custom:simple-clock-card
use_military: true
hide_seconds: true
font_size: 4rem
padding_size: 3.4rem
tap_action:
  action: navigate
  navigation_url: /schedule
```

Here's an example. I use the /schedule dashboard for setting alarms.
